### ISSUE TITLE
Installing from google does not work !!

### ISSUE THREAD

**Issue by rjpg** [muaz-khan/Chrome-Extensions#101]
[https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk](https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk)

"
404. That’s an error.

The requested URL was not found on this server. That’s all we know.

"

**Comment by muaz-khan** [comment]
**Google removed it** from their store (themselves).
