### ISSUE TITLE
chrome extension is not working when installed from source

### ISSUE THREAD

**Issue by manurajmr1** [muaz-khan/Chrome-Extensions#15]
https://www.youtube.com/watch?v=nBUuMKtEeyU

As refered from this video, screen capturing doesnt worked for me, when installed from https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture.  But the chrome webstore extension was working perfectly.

i manually installed the extension using developer mode in chrome and used it. and even if i change the extension id  it is still poiting to chrome-extension://**ajhifddimkapgcifgcodmmfdlknahffk**/icon.png which is the default id, is this is what causing the issue ?.

This is the error am getting on the console
**Failed to load resource: net::ERR_FAILED chrome-extension://ajhifddimkapgcifgcodmmfdlknahffk/icon.png
Screen-Sharing.html:148 Uncaught not-installed**

and i tried this URL https://localhost:9001/demos/Screen-Sharing.html
Please help!

**Comment by muaz-khan** [comment]
Modify [matches](https://github.com/muaz-khan/Chrome-Extensions/blob/master/desktopCapture/manifest.json#L17) line to point `https://localhost:9001/`:

```json
{
    "content_scripts": [ {
       "matches": ["https://localhost:9001/*"]
    }]
}
```

Now click `reload` link from the `chrome://extensions` page.

Now, remove `getScreenId.js` from the [`screen-sharing.html`](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/screen-sharing.html) demo:

```html
<!--
<script src="https://cdn.webrtc-experiment.com:443/getScreenId.js"></script>
-->
```

Remove following block from the same demo page (`screen-sharing.html`):

```javascript
/*
connection.getScreenConstraints = function(callback) {
    getScreenConstraints(function(error, screen_constraints) {
        if (!error) {
            screen_constraints = connection.modifyScreenConstraints(screen_constraints);
            callback(error, screen_constraints);
            return;
        }
        throw error;
    });
};
*/
```

Now reload `https://localhost:9001/demos/Screen-Sharing.html` and it will work. It will try to use your local chrome extension.

**Comment by manurajmr1** [comment]
OK this worked great. Is there any way that i can check whether the extension is installed using detect RTC.

It worked for me using the default extension  "ajhifddimkapgcifgcodmmfdlknahffk"
extensionid = window.RMCExtensionID || 'ajhifddimkapgcifgcodmmfdlknahffk';

But when i use the above method (my own extension) the extension id keeps on changing as i don't want to upload it into chromestore. Is there any other way to check this extension is installed that ill be helpful.

**Comment by muaz-khan** [comment]
If you deploy chrome-extension on Google Web Store, then `connection.getChromeExtensionStatus` will work as well:

* https://chrome.google.com/webstore/developer/dashboard

**Comment by muaz-khan** [comment]
PS. `getScreenId.js` supports this: (in case if you're using getScreenId)

```javascript
window.getChromeExtensionStatus(function(status) {
    alert(status); // installed-enabled etc.
});
```

**Comment by Xanthony89X** [comment]
Huh
