### ISSUE TITLE
how to convert file into video file 

### ISSUE THREAD

**Issue by dinesh-pathak100** [muaz-khan/Chrome-Extensions#26]
Sir how can I convert the simple file like 
`var file = new File([blob ? blob : ''], getFileName(fileExtension), {
        type: mimeType
    });` 
 into video file.
Sir our video blob is like 

> blob:chrome-extension://hgpenkfjeddjngnojmcmgbclkoakihhg/b3232e95-f571-4d8a-a272-a79534129c21 

and here is another recorder _screencastify_  whose video blob is like 

> filesystem:chrome-extension://mmeijimgabbpbgpdklnllpncmdofkcpn/persistent/b04ac04e-bedf-455d-y7e5-998ff77b92d3.webm

I need this video blob because there is problem in video that controls are not working
how can I get this video blob. Sir please help thank you @muaz-khan

**Comment by muaz-khan** [comment]
Both links are accessible merely on your own system.

Those guys seems using `requestFileSystem` API where `fileEntry` object has `toURL` method which returns something like this:

```javascript
filesystem:chrome-extension://mmeijimgabbpbgpdklnllpncmdofkcpn/persistent/b04ac04e-bedf-455d-y7e5-998ff77b92d3.webm
```

Please check this article for how to use `requestFileSystem` API: <a href="https://www.html5rocks.com/en/tutorials/file/filesystem/">https://www.html5rocks.com/en/tutorials/file/filesystem/</a>

**Comment by dinesh-pathak100** [comment]
Sir where this should be used on background or in client side where video is generated like preview.js[https://github.com/muaz-khan/Chrome-Extensions/blob/master/screen-recording/preview/preview.js](url)

**Comment by dinesh-pathak100** [comment]
thank you so much sir

**Comment by rizkiiiiiiiiiiiiiiiiiii** [comment]
mmeijimgabbpbgpdklnllpncmdofkcpn.
Oi I got random redirection to some ad-sites.
tf is goin' on?
i'ts 2020!
