### ISSUE TITLE
Screen + microphone + system audio

### ISSUE THREAD

**Issue by nch7** [muaz-khan/Chrome-Extensions#29]
There is an option to record full screen + microphone and screen + system audio.

Is it possible to record all 3 at the same time?

**Comment by gijo-varghese** [comment]
+1

**Comment by safilsunny** [comment]
+1

**Comment by LiuTing0403** [comment]
+1

**Comment by iAziz786** [comment]
+1

**Comment by sidgeek** [comment]
+1

**Comment by muaz-khan** [comment]
It is already implemented:
![recordrtc](https://user-images.githubusercontent.com/477092/50946735-90f6a080-14bc-11e9-8d2d-b47614cac42a.png)
* https://chrome.google.com/webstore/detail/recordrtc/ndcljioonkecdnaaihodjgiliohngojp

**Comment by tantalate** [comment]
> It is already implemented:
> ![recordrtc](https://user-images.githubusercontent.com/477092/50946735-90f6a080-14bc-11e9-8d2d-b47614cac42a.png)
> 
> * https://chrome.google.com/webstore/detail/recordrtc/ndcljioonkecdnaaihodjgiliohngojp

Hi, I would like to ask if there is a way to broadcast all these media sources at the same time via WebRTC.
Webcam + Microphone + screen + system audio would be better.

Thank you very much.
