### ISSUE TITLE
ipad viewing not working

### ISSUE THREAD

**Issue by philippe1970** [muaz-khan/Chrome-Extensions#5]
ipad refuses to show the content of the shared screen. All android phones and tablets work fine.
upgraded ipad to ios 10, same issue.
Safari, Chrome are not working only showing a blue line. However when viewing the same content on android, the webrtx show "2 users are viewing your screen!". But ipad is viewing a blue line only.

How can I fix this?

**Comment by inspiraluna** [comment]
this is not a problem of this extension. since ios-chrome or safar does not allow any webrtc related stuff. (only within apps)
