### ISSUE TITLE
how can i use this to stream to a different server? (Eg; like using Kurento Media Server)

### ISSUE THREAD

**Issue by vimukthimudalige** [muaz-khan/Chrome-Extensions#52]

**Comment by muaz-khan** [comment]
For your information, there are two demo files:
1. [shareStreamUsingAntMediaServer.js](https://github.com/muaz-khan/Chrome-Extensions/blob/master/desktopCapture-p2p/background/shareStreamUsingAntMediaServer.js)
2. [shareStreamUsingRTCMultiConnection.js](https://github.com/muaz-khan/Chrome-Extensions/blob/master/desktopCapture-p2p/background/shareStreamUsingRTCMultiConnection.js)
