### ISSUE TITLE
Recording doesn't start

### ISSUE THREAD

**Issue by beiyingz** [muaz-khan/Chrome-Extensions#6]
Chrome browser version: Version 53.0.2785.143 (64-bit)

This plugin used to work, not anymore.  Is it because Chrome 53?

**Comment by muaz-khan** [comment]
Open this page:

* https://www.webrtc-experiment.com/DetectRTC/

Click the extension icon; and it MUST work on both Windows7 and Mac.

Hints:

1. Open "Options" page and enable ONLY  "Microphone". Do NOT set "Audio+Tab".
2. Open any HTTPs page and click the extension icon
3. Windows 10 or Ubuntu may NOT work; so try on Win7 or MacOSX.

A short recorded video using Chrome 53 on Win7:

* https://www.youtube.com/watch?v=sZ2cKkAZiXw

> Facebook, GMail, Github etc. does NOT allows embedded scripts. That's why please either try to open `https://rtcxp.com` or `https://google.com` or `https://webrtc-experiment.com` so that the extension can inject JavaScript to capture your microphone.
