### ISSUE TITLE
Chrome 71 issue with getusermedia

### ISSUE THREAD

**Issue by nkotha** [muaz-khan/Chrome-Extensions#63]
I am using recordrtc chrome extension on chrome 71 and ran into catch when trying to getUserMedia. It works fine on chrome 70. Please suggest any changes that needs to done in specific to chrome 71.

var constraints = {
    audio: true,
    video: true
};

navigator.mediaDevices.getUserMedia(constraints).then(function(stream) {
   //success
}).catch(function() {
    document.querySelector('h1').innerHTML = 'Unable to capture your microphone.';
});

**Comment by CRswallow** [comment]
Hello, has this issue been resolved?
