### ISSUE TITLE
Hide "Stop sharing" pop up?

### ISSUE THREAD

**Issue by cristianocoelho** [muaz-khan/Chrome-Extensions#7]
Is this possible? I'm using this extension with getScreenId javascript library in order to get the stream/id from it, and the idea is to close the stream from code (aka stop sharing button).

However, if the user uses the stop sharing from the extension, there's no callback to detect the stream died, isnt it? Some help can be appreciated.

**Comment by miguelrcDEV** [comment]
+1

**Comment by muaz-khan** [comment]
Please check this:

* https://www.webrtc-experiment.com/webrtcpedia/#stream-ended-listener
