### ISSUE TITLE
 desktop-capturing.js is not found

### ISSUE THREAD

**Issue by Bharadhan** [muaz-khan/Chrome-Extensions#94]
I want to use this extension for my own test purpose I searched for the file  desktop-capturing.js which you have mentioned in the developer notes to change the resultingURL variable how can I do that if the file is not present.

Please guide me

![image](https://user-images.githubusercontent.com/5784711/76728925-f9ef3d80-677d-11ea-8ea9-578576417ab8.png)

**Comment by muaz-khan** [comment]
It is here:

* https://github.com/muaz-khan/Chrome-Extensions/blob/master/desktopCapture-p2p/background/shareStreamUsingRTCMultiConnection.js#L130

**Comment by Bharadhan** [comment]
How can I get my own stun server credentails

**Comment by muaz-khan** [comment]
Install "coTURN" (recommended) or oherwise NPM packaged named as "stun".

**Comment by Bharadhan** [comment]
In windows OK

**Comment by Bharadhan** [comment]
I have installed the stun server is there any command creating my own credentials can you direct me on that
